In [9]:
import chess
import chess.pgn
import matplotlib.pyplot as plt
import numpy as np
from IPython import display
import time
from sklearn import preprocessing

In [2]:
path = 'lichess_NotGmSule_2023-02-01.pgn'

In [3]:
file = open(path, encoding="utf-8")
games = []
a = chess.pgn.read_game(file)
while a:
    games.append(a)
    try:
        a = chess.pgn.read_game(file)
    except:
        print(f'could not read game number {len(games)}')

In [4]:
len(games)

134

In [10]:
def make_move(uci):
    '''
    returns the two postions of the uci(Universal Chess Interface) format
    '''
    pos1 = uci[:2]
    pos2 = uci[2:4]
    return (chess.parse_square(pos1), chess.parse_square(pos2))


In [5]:
def get_moves(game):
    moves = []
    for i in game.mainline_moves():
        moves.append(i)
    return moves

In [6]:
get_moves(games[0])

[Move.from_uci('e2e4'),
 Move.from_uci('c7c6'),
 Move.from_uci('f2f4'),
 Move.from_uci('d7d5'),
 Move.from_uci('g2g3'),
 Move.from_uci('d5e4'),
 Move.from_uci('g1e2'),
 Move.from_uci('c8g4'),
 Move.from_uci('h2h3'),
 Move.from_uci('g4e2'),
 Move.from_uci('d1e2'),
 Move.from_uci('g8f6'),
 Move.from_uci('g3g4'),
 Move.from_uci('f6d5'),
 Move.from_uci('c2c4'),
 Move.from_uci('d5b6'),
 Move.from_uci('e2e4'),
 Move.from_uci('e7e6'),
 Move.from_uci('f4f5'),
 Move.from_uci('f8e7'),
 Move.from_uci('f5e6'),
 Move.from_uci('f7e6'),
 Move.from_uci('f1d3'),
 Move.from_uci('g7g6'),
 Move.from_uci('b1c3'),
 Move.from_uci('b8d7'),
 Move.from_uci('c4c5'),
 Move.from_uci('d7c5'),
 Move.from_uci('e1g1'),
 Move.from_uci('c5e4'),
 Move.from_uci('d3e4'),
 Move.from_uci('b6c4'),
 Move.from_uci('f1f4'),
 Move.from_uci('c4e5'),
 Move.from_uci('g4g5'),
 Move.from_uci('e5d3'),
 Move.from_uci('b2b3'),
 Move.from_uci('d3f4'),
 Move.from_uci('c3a4'),
 Move.from_uci('d8d4'),
 Move.from_uci('g1f1'),
 Move.from_uci('

In [8]:
def make_move(uci):
    '''
    returns the two postions of the uci(Universal Chess Interface) format
    '''
    pos1 = uci[:2]
    pos2 = uci[2:4]
    return (chess.parse_square(pos1), chess.parse_square(pos2))


In [57]:
le = preprocessing.LabelEncoder()

# funtion to label encode every board state in a game

def label_encode_game(game):
    board = game.board()
    moves = get_moves(game)
    encoded_moves = []
    for move in moves:
        board.push(move)
        encoded_moves.append(le.fit_transform(board.fen().split(' ')[0].split('/')))
    return encoded_moves

In [ ]:
def label_encode_state(board):
    return le.fit_transform(board.fen().split(' ')[0].split('/'))

In [73]:
games[0][0].board().fen().split(' ')[0].split('/')

['rnbqkbnr', 'pppppppp', '8', '8', '4P3', '8', 'PPPP1PPP', 'RNBQKBNR']

In [18]:
def label_encode_board(board):
    return le.fit_transform(board.fen().split(' ')[0].split('/'))

In [58]:
label_encode_game(games[0])

[array([5, 4, 1, 1, 0, 1, 2, 3], dtype=int64),
 array([6, 5, 0, 2, 1, 2, 3, 4], dtype=int64),
 array([6, 5, 0, 2, 1, 2, 3, 4], dtype=int64),
 array([7, 6, 0, 1, 2, 3, 4, 5], dtype=int64),
 array([7, 6, 0, 1, 2, 3, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 1, 2, 3, 4, 5], dtype=int64),
 array([7, 6, 1, 2, 0, 3, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6, 0, 2, 1, 3, 4, 5], dtype=int64),
 array([7, 6, 0, 2, 1, 3, 4, 5], dtype=int64),
 array([7, 6, 0, 3, 1, 2, 4, 5], dtype=int64),
 array([7, 6,

In [74]:
from sklearn.preprocessing import LabelEncoder

def label_encode_board(board_state):
    # Define dictionary for mapping chess pieces to string labels
    piece_labels = {
        'p': 'pawn_black', 'P': 'pawn_white',
        'n': 'knight_black', 'N': 'knight_white',
        'b': 'bishop_black', 'B': 'bishop_white',
        'r': 'rook_black', 'R': 'rook_white',
        'q': 'queen_black', 'Q': 'queen_white',
        'k': 'king_black', 'K': 'king_white',
        '.': 'empty' # add mapping for empty squares
    }

    # Convert board_state string to list of individual piece labels
    pieces = [piece_labels.get(piece, 'empty') for piece in board_state]

    # Create instance of LabelEncoder
    encoder = LabelEncoder()

    # Fit and transform the list of piece labels using the LabelEncoder
    encoded_pieces = encoder.fit_transform(pieces)

    # Reshape the encoded pieces into a 2D 8x8 array
    # matrix = encoded_pieces.reshape(8, 8)

    return encoded_pieces


In [75]:
label_encode_board(games[0].board().fen().split(' ')[0])

array([11,  5,  0,  9,  3,  0,  5, 11,  2,  7,  7,  7,  7,  7,  7,  7,  7,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  8,  8,  8,  8,  8,  8,  8,  8,
        2, 12,  6,  1, 10,  4,  1,  6, 12], dtype=int64)

In [ ]:
# turn fen into a 64x12 matrix

def fen_to_matrix(fen):

    

In [77]:
import numpy as np
import chess
from sklearn.preprocessing import LabelEncoder

def label_encode_board(board_state):
    # Define dictionary for mapping chess pieces to string labels
    piece_labels = {
        'p': 'pawn_black', 'P': 'pawn_white',
        'n': 'knight_black', 'N': 'knight_white',
        'b': 'bishop_black', 'B': 'bishop_white',
        'r': 'rook_black', 'R': 'rook_white',
        'q': 'queen_black', 'Q': 'queen_white',
        'k': 'king_black', 'K': 'king_white',
        '.': 'empty' # add mapping for empty squares
    }

    # Parse the FEN string to obtain the positions of the pieces on the board
    board = chess.Board(board_state)
    pieces = board.piece_map()

    # Initialize an 8x8 matrix to represent the board
    matrix = np.zeros((8, 8), dtype=int)

    # Iterate over the pieces on the board and fill in the matrix with their encoded values
    for square, piece in pieces.items():
        rank, file = chess.square_rank(square), chess.square_file(square)
        label = piece_labels.get(piece.symbol(), 'empty')
        encoder = LabelEncoder()
        encoded_label = encoder.fit_transform([label])[0]
        matrix[rank][file] = encoded_label

    return matrix


In [82]:
label_encode_board(games[1].board().fen())

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [92]:
import numpy as np
import chess

def get_piece_type(piece):
    # Helper function to get the type of a chess piece (with color information)
    if piece is None:
        return None
    elif piece.color == chess.WHITE:
        if piece.piece_type == chess.PAWN:
            return 'P'
        elif piece.piece_type == chess.KNIGHT:
            return 'N'
        elif piece.piece_type == chess.BISHOP:
            return 'B'
        elif piece.piece_type == chess.ROOK:
            return 'R'
        elif piece.piece_type == chess.QUEEN:
            return 'Q'
        elif piece.piece_type == chess.KING:
            return 'K'
    elif piece.color == chess.BLACK:
        if piece.piece_type == chess.PAWN:
            return 'p'
        elif piece.piece_type == chess.KNIGHT:
            return 'n'
        elif piece.piece_type == chess.BISHOP:
            return 'b'
        elif piece.piece_type == chess.ROOK:
            return 'r'
        elif piece.piece_type == chess.QUEEN:
            return 'q'
        elif piece.piece_type == chess.KING:
            return 'k'

def get_board_matrix(board_state):
    # Initialize an 8x8 matrix to represent the board
    matrix = np.zeros((8, 8), dtype=str)

    # Parse the board_state string to obtain the positions of the pieces on the board
    board = chess.Board(board_state)
    for row in range(8):
        for col in range(8):
            # Get the square index corresponding to the current row and column
            square = chess.square(col, 7 - row)

            # Get the type of the piece occupying the current square (if any)
            piece_type = get_piece_type(board.piece_at(square))

            # Store the piece type in the matrix
            matrix[row][col] = piece_type or '.'

    return matrix


In [93]:
get_board_matrix(games[0].board().fen())

array([['r', 'n', 'b', 'q', 'k', 'b', 'n', 'r'],
       ['p', 'p', 'p', 'p', 'p', 'p', 'p', 'p'],
       ['.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.'],
       ['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P'],
       ['R', 'N', 'B', 'Q', 'K', 'B', 'N', 'R']], dtype='<U1')

In [94]:
le = preprocessing.LabelEncoder()
le.fit_transform(get_board_matrix(games[0].board().fen()).flatten())

array([12,  9,  7, 11,  8,  7,  9, 12, 10, 10, 10, 10, 10, 10, 10, 10,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  4,  4,
        4,  4,  4,  4,  4,  6,  3,  1,  5,  2,  1,  3,  6], dtype=int64)

In [95]:
# iterate through all the moves in a game and label encode them

def label_encode_game(game):
    board = game.board()
    moves = get_moves(game)
    encoded_moves = []
    for move in moves:
        board.push(move)
        encoded_moves.append(le.fit_transform(get_board_matrix(board.fen()).flatten()))
    return encoded_moves

In [96]:
label_encode_game(games[0])

[array([12,  9,  7, 11,  8,  7,  9, 12, 10, 10, 10, 10, 10, 10, 10, 10,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  4,  4,
         4,  0,  4,  4,  4,  6,  3,  1,  5,  2,  1,  3,  6], dtype=int64),
 array([12,  9,  7, 11,  8,  7,  9, 12, 10, 10,  0, 10, 10, 10, 10, 10,  0,
         0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  4,  4,
         4,  0,  4,  4,  4,  6,  3,  1,  5,  2,  1,  3,  6], dtype=int64),
 array([12,  9,  7, 11,  8,  7,  9, 12, 10, 10,  0, 10, 10, 10, 10, 10,  0,
         0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  4,  4,
         4,  0,  0,  4,  4,  6,  3,  1,  5,  2,  1,  3,  6], dtype=int64),
 array([12,  9,  7, 11,  8,  7,  9, 12, 10, 10,  0,  0, 10, 10, 10, 10,  0,
         0, 10,